# Generated by Django 3.1.2 on 2020-10-31 16:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
